### ISSUE TITLE
Suggestion for making location a standard object used by org and node

### ISSUE THREAD

**Issue by michaeljyeates** [eosrio/bp-info-standard#1]
I propose that we create a standard location object such as 

`{
'name': "London',
'country': 'GB',
'latitude':0.1,
'longitude:50
}`

Then we can create a top-level `org` object which has location as a property.  Each node could also have a location attribute so that geospacial data is consistent

**Comment by igorls** [comment]
@michaeljyeates included on revision a852819f6a8a183f40913222b75dbafc4a44c18a
