### ISSUE TITLE
Attribute not described in documentation 

### ISSUE THREAD

**Issue by xavier506** [eosrio/bp-info-standard#15]
The attribute  "node_type" is not described in the readme documentation. What value types are expected for this key?

https://github.com/eosrio/bp-info-standard/blob/0fe996e113e754c3dc8fd3588e42d5c637510dce/bp.json#L56

**Comment by matthewdarwin** [comment]
Also it would be good to understand what exactly is meant by each one of the types: "producer", "full", "query"

**Comment by matthewdarwin** [comment]
https://github.com/eosrio/bp-info-standard/pull/16

**Comment by eosrio** [comment]
Merged.
