### ISSUE TITLE
Add Testnet Nodes Info  / Chain Id info in Nodes json

### ISSUE THREAD

**Issue by gaboesquivel** [eosrio/bp-info-standard#23]
What do you think about adding testnets info to the bp.json?

```
testnet_nodes: [
   "jungle" : [{},{}],
   "ghostbusters" : [{},{}],
   "scholar" : [{},{}],
]
```

Each bp can serve a different bp.json for each testnet as well, however I think it convenient to have them all in one place.

**Comment by gaboesquivel** [comment]
another alternative is adding `chain_id` in the nodes info

**Comment by matthewdarwin** [comment]
If we're doing this, I like the chain_id suggestion better.   The original proposal of having multiple bp.json files and then merge them seems like too much work.   chain_id is pretty clear and is extendable to any other network.

**Comment by gaboesquivel** [comment]
Yes, agree. I like that solution better as well. 
We would also have to change the `producer_public_key` to an array.
It's not so trivial supporting multiple networks, actually. 
But definitively better all in one file IMO.
`bp.json` at the organization level and not at the network level.

something like this

```js
{
   org: {}, // as is right now
   accounts:[
    { account_name, producer_public_key, <chain_id> },
    { account_name, producer_public_key, <chain_id> },
   ],
   nodes: [
     {...otherData, <chain_id>}, 
     {...otherData, <chain_id>}
   ]
}
```

**Comment by gaboesquivel** [comment]
We can still keep `producer_public_key` at the root level as mainnet producer key for backward compatibility

**Comment by gaboesquivel** [comment]
I just realized we already have a standard for this.

https://github.com/eosrio/bp-info-standard#overriding-jsons-for-specific-chains

it would be nice to use also network name.  
Eg. `bp.jungle.json`, `bp.gosthbusters.json` `bp.scholar.json` .
