### ISSUE TITLE
bp.json on-chain does not match the one provided in regproducer URL

### ISSUE THREAD

**Issue by samspk** [eosrio/bp-info-standard#25]
We have published bp.json on Blockchain.. But where is miss-match? What is not matching? More specific information is needed...

![image](https://user-images.githubusercontent.com/39917017/43790996-879a90e0-9a74-11e8-8d37-e75ce858f877.png)

**Comment by igorls** [comment]
Please contact EOS Nation for anything regarded to their validation website. @DenisCarriere
