### ISSUE TITLE
Add an optional array of URLs linking to projects which benefit the community

### ISSUE THREAD

**Issue by lukestokes** [eosrio/bp-info-standard#27]
Based on a recent [conversation with a BP ratings group](https://steemit.com/eos/@controllinghand/just-the-facts-eos-proxy-by-eosratings-com#@controllinghand/re-lukestokes-re-controllinghand-re-lukestokes-re-controllinghand-just-the-facts-eos-proxy-by-eosratings-com-20181020t210938753z), the idea of linking to useful projects came up which makes a lot of sense to me. It would still be up to the community to evaluate that BPs level of involvement in the project or how beneficial that project really is to the greater ecosystem, but I think it might be an interesting way for BPs to quickly communicate to others what they are into. Yes, their website will probably do this also, but having it part of the BP.json standard would help others quickly aggregate this information in a useful way for voters.

What do you think?

**Comment by controllinghand** [comment]
Another alternative to the BP.json file could be a smart contract that BPs can use to register said tool/app/education/resource etc.  I'm thinking this could be something in the vain of [how proxy account register today](https://github.com/AlohaEOS/eos-proxyinfo) 
I would like to see something like
EOS account name: Your EOS account name. If a BP should be the one that they use to produce blocks so they get the credit.
Project Name:  This could be the name of the tool,app,topic etc...
Description:  A short description of your project intended to be shown in listings.
Website: An http or https URL to a website, Reddit post, etc. with more information about your Project.
Logo: An http or https URL to an image with the size of 256 x 256 px.  This should be the logo for the project not the BP's main logo
Project Status:  Is this in Dev, Beta or Production
Category: *This is optional*  I have some categories I have already created located here https://eosratings.com/top-tools/ for example, explorers, wallets, voting, resources, outreach, education, testnet, key managment, identity, account creation, chain contracts, and a host of monitors and trackers.

**Comment by lukestokes** [comment]
A smart contract would be great, but I wonder if RAM tables would be the best place to store that information since it wouldn't really be needed for on-chain calculations. EOS needs more storage solutions which are easy for people to use. Also, I'd like to see more of the community adopting Schema.org standards like https://pending.schema.org/Project We're trying to do that with <a href="https://github.com/eosdac/eosdactoolkit/issues/2#issuecomment-406934891">our member profiles</a>.

**Comment by igorls** [comment]
https://github.com/eosrio/bp-info-standard/commit/b9917254144f060994405b11232ae59a7cc75624
other_resources array is sufficient to solve this issue

**Comment by igorls** [comment]
closing this issue for now, please re-open it if needed
