### ISSUE TITLE
Extension of bp-info-standard

### ISSUE THREAD

**Issue by rakeden** [eosrio/bp-info-standard#37]
Currently we are experience an increase of API services being introduced to Antelope chains.

Therefore we proposed to add the following services to the standard, namely:

- "light-api"
- "ipfs"

What do you think of the proposal?
When can we expect those services to be added to the [documentation](https://github.com/eosrio/bp-info-standard#api-features)?

**Comment by igorls** [comment]
thanks for the suggestion, it is included in the schema now - https://github.com/eosrio/bp-info-standard/commit/469ce4e8fbd9f863deb92e46beb47eccd65aacbc

**Comment by rakeden** [comment]
Thanks for the update!
